### PR TITLE
Revert "fixed #17"

### LINKED ISSUE #17: issue-github-2

### PR DESCRIPTION
**Pull request by fn-zerkoc**
Reverts vlvn-test/atlas#18

### CODE REVIEW

**Comment by fn-zerkoc** [comment]
submitter 1

**Comment by zerkoc** [comment]
reviewer-1

**Comment by zerkoc** [comment]
> submitter 1
reviwer-2

**Comment by zerkoc** [comment]
reviewer-3 @fn-zerkoc

**Pull request merged**
